<?php

declare(strict_types=1);

namespace Simplee\FredConnector;

/**
 * Protocol/framework constants shared across Talk to Fred WordPress
 * connectors. Connector-specific values (option keys, branding) are NOT
 * here — they are injected by the consumer.
 *
 * Generated by lifting the constants referenced by the shared classes (and
 * their tests) from the WooCommerce vendor connector; values are identical
 * across connectors except branding-flavored ones, which are injected.
 */
final class Constants
{
    public const HTTP_OK = 200;
    public const HTTP_FOUND = 302;
    public const HTTP_BAD_REQUEST = 400;
    public const HTTP_NOT_FOUND = 404;
    public const HTTP_SERVICE_UNAVAILABLE = 503;
    public const API_ENDPOINT_QOS_SCHEMA = '/v1/vendor/qos/schema';
    public const HEADER_AUTHORIZATION = 'Authorization';
    public const HEADER_CONTENT_TYPE = 'Content-Type';
    public const HEADER_ACCEPT = 'Accept';
    public const HEADER_BEARER_PREFIX = 'Bearer ';
    public const CONTENT_TYPE_JSON = 'application/json';
    public const DEFAULT_TIMEOUT_SECONDS = 30;
    public const DEFAULT_CONNECT_TIMEOUT_SECONDS = 10;
    public const QOS_UNLIMITED = -1;
    public const PROVIDER_OPENAI = 'openai';
    public const PROVIDER_CLAUDE = 'claude';
    public const PROVIDER_GEMINI = 'gemini';
    public const PROVIDER_GROK = 'grok';
    public const PROVIDER_ELEVENLABS = 'elevenlabs';
    public const PROVIDER_SLUGS = [
        self::PROVIDER_OPENAI,
        self::PROVIDER_CLAUDE,
        self::PROVIDER_GEMINI,
        self::PROVIDER_GROK,
        self::PROVIDER_ELEVENLABS,
    ];
    public const DOF_CHAT_RPM = 'chat_rpm';
    public const DOF_RAG_QUERY_RPM = 'rag_query_rpm';
    public const DOF_REALTIME_VOICE_ENABLED = 'realtime_voice_enabled';
    public const DOF_LLM_PROVIDERS = 'llm_providers';
    public const HANDOFF_SURFACE_ADMIN = 'admin';
    public const HANDOFF_SURFACE_USER = 'user';
    public const HANDOFF_PRINCIPAL_KIND_USER = 'user';
    public const HANDOFF_PRINCIPAL_KIND_GROUP = 'group';
    public const HANDOFF_FILTER_RESOLVE_PRINCIPAL = 'fred_cloud_resolve_principal';
    public const HANDOFF_FILTER_RESOLVE_SURFACE = 'fred_cloud_resolve_surface';
    public const ROLE_ADMINISTRATOR = 'administrator';
    public const ROLE_SHOP_MANAGER = 'shop_manager';
    public const ROLE_SVA_AGENCY_ADMIN = 'sva_agency_admin';
    public const ROLE_SVA_CLIENT_ADMIN = 'sva_client_admin';
    public const ROLE_CUSTOMER = 'customer';
    public const ROLE_SUBSCRIBER = 'subscriber';
    public const ADMIN_SURFACE_ROLES = [
        self::ROLE_ADMINISTRATOR,
        self::ROLE_SHOP_MANAGER,
        self::ROLE_SVA_AGENCY_ADMIN,
        self::ROLE_SVA_CLIENT_ADMIN,
    ];
    public const USER_SURFACE_ROLES = [
        self::ROLE_CUSTOMER,
        self::ROLE_SUBSCRIBER,
    ];
    public const OIDC_ROUTE_JWKS = '/jwks';
    public const OIDC_ROUTE_AUTHORIZE = '/authorize';
    public const OIDC_ROUTE_TOKEN = '/token';
    public const OIDC_ROUTE_USERINFO = '/userinfo';
    public const OIDC_RESPONSE_TYPE_CODE = 'code';
    public const OIDC_GRANT_AUTHORIZATION_CODE = 'authorization_code';
    public const OIDC_PKCE_METHOD_S256 = 'S256';
    public const OIDC_ALG_EDDSA = 'EdDSA';
    public const OIDC_KTY_OKP = 'OKP';
    public const OIDC_CRV_ED25519 = 'Ed25519';
    public const OIDC_KEY_USE_SIG = 'sig';
    public const OIDC_SUBJECT_TYPE_PUBLIC = 'public';
    public const OIDC_SCOPE_OPENID = 'openid';
    public const OIDC_SCOPE_PROFILE = 'profile';
    public const OIDC_SCOPE_EMAIL = 'email';
    public const OIDC_LOGIN_PORTAL_CLIENT_ID_DEFAULT = 'fred-login-portal';
    public const OIDC_LOGIN_PORTAL_REDIRECT_URI_DEFAULT = 'https://login.talktofred.ai/v1/auth/oidc/callback';
    public const OIDC_LOGIN_PORTAL_DEFAULT_ENABLED = true;
    public const OIDC_AUTH_CODE_TTL_SECONDS = 60;
    public const OIDC_ACCESS_TOKEN_TTL_SECONDS = 3600;
    public const OIDC_ID_TOKEN_TTL_SECONDS = 3600;
    public const OIDC_CODE_TRANSIENT_PREFIX = 'fred_cloud_oidc_code_';
    public const OIDC_DEFAULT_API_AUDIENCE = 'fred-adapter';
    public const OIDC_DEFAULT_ADMIN_SCOPES = [
        'fred:admin:*',
        'fred:platform:*',
    ];
    public const OIDC_DEFAULT_USER_SCOPES = [
        'fred:user:*',
        'fred:ecom:*',
        'fred:data:read',
    ];
    public const OIDC_FILTER_CLIENTS = 'fred_cloud_oidc_clients';
    public const API_ENDPOINT_UPDATES_CHECK = '/api/v1/updates/check';
    public const API_ENDPOINT_DOWNLOADS_AUTHORIZE = '/api/v1/downloads/authorize';
    public const API_ENDPOINT_UPDATES_DOWNLOAD = '/api/v1/updates/download';
    public const UPDATE_CHECK_CACHE_TTL_SECONDS = 86400;
    public const UPDATE_CHECK_CACHE_NO_UPDATE_TTL_SECONDS = 300;
    public const UPDATE_TRANSIENT_PREFIX = 'fred_connector_update_check_';
    public const UPDATE_TRANSIENT_VERSION_SEPARATOR = '_v';
    public const UPDATE_TRANSIENT_VERSION_SANITIZE_PATTERN = '/[^A-Za-z0-9._-]+/';
    public const UPDATE_TRANSIENT_VERSION_SANITIZE_REPLACEMENT = '_';
    public const UPDATE_REST_NAMESPACE = 'fred-cloud-updates/v1';
    public const UPDATE_REST_ROUTE_DOWNLOAD = '/download/(?P<slug>[A-Za-z0-9._-]+)';
    public const UPDATE_REST_ROUTE_DOWNLOAD_PATH_PREFIX = '/download/';
    public const UPDATE_REST_PARAM_SLUG = 'slug';
    public const UPDATE_REST_QUERY_PARAM_REST_ROUTE = 'rest_route';
    public const UPDATE_DOWNLOAD_TIMEOUT_SECONDS = 300;
    public const WP_FILTER_PRE_SET_SITE_TRANSIENT_UPDATE_PLUGINS = 'pre_set_site_transient_update_plugins';
    public const WP_FILTER_PLUGINS_API = 'plugins_api';
    public const WP_FILTER_UPGRADER_PRE_DOWNLOAD = 'upgrader_pre_download';
    public const WP_FILTER_UPGRADER_PRE_DOWNLOAD_ARG_COUNT = 4;
    public const WP_ACTION_DELETE_SITE_TRANSIENT_UPDATE_PLUGINS = 'delete_site_transient_update_plugins';
    public const WP_ACTION_REST_API_INIT = 'rest_api_init';
    public const PLUGINS_API_ACTION_INFORMATION = 'plugin_information';
    public const WORDPRESS_FILTER_ALLOWED_REDIRECT_HOSTS = 'allowed_redirect_hosts';
    public const UPDATE_PAYLOAD_KEY_LICENSE_KEY = 'license_key';
    public const UPDATE_PAYLOAD_KEY_DOMAIN = 'domain';
    public const UPDATE_PAYLOAD_KEY_SLUG = 'slug';
    public const UPDATE_PAYLOAD_KEY_PRODUCT_SLUG = 'product_slug';
    public const UPDATE_PAYLOAD_KEY_CURRENT_VERSION = 'current_version';
    public const UPDATE_PAYLOAD_KEY_IS_PRERELEASE = 'is_prerelease';
    public const UPDATE_PAYLOAD_KEY_VERSION = 'version';
    public const UPDATE_RESPONSE_KEY_SUCCESS = 'success';
    public const UPDATE_RESPONSE_KEY_UPDATE = 'update';
    public const UPDATE_RESPONSE_KEY_UPDATE_AVAILABLE = 'update_available';
    public const UPDATE_RESPONSE_KEY_LATEST_VERSION = 'latest_version';
    public const UPDATE_RESPONSE_KEY_DOWNLOAD_URL = 'download_url';
    public const UPDATE_RESPONSE_KEY_TESTED_WP = 'tested_wp';
    public const UPDATE_RESPONSE_KEY_MIN_WP = 'min_wp';
    public const UPDATE_RESPONSE_KEY_CHANGELOG = 'changelog';
    public const UPDATE_VERSION_PATTERN = '/^[0-9]+(?:\.[0-9]+)*(?:[-+][0-9A-Za-z.-]+)?$/';
    public const HEADER_CACHE_CONTROL = 'Cache-Control';
    public const HEADER_CACHE_CONTROL_NO_STORE = 'no-store, no-cache, must-revalidate, private, max-age=0';
    public const REST_ERROR_CODE_SLUG_MISMATCH = 'fred_cloud_update_slug_mismatch';
    public const REST_ERROR_CODE_DOWNLOAD_UNAVAILABLE = 'fred_cloud_update_download_unavailable';
    public const REST_ERROR_MESSAGE_SLUG_MISMATCH = 'Requested slug does not match this plugin instance.';
    public const REST_ERROR_MESSAGE_DOWNLOAD_UNAVAILABLE = 'License download authorization is currently unavailable.';
    public const REST_ERROR_MESSAGE_DOWNLOAD_UNAVAILABLE_WITH_STAGE = 'License download authorization is currently unavailable (stage: %s).';
    public const UPDATE_LOG_PREFIX = '[Fred Connector Update] ';
    public const UPDATE_LOG_PROXY_DOWNLOAD_UNAVAILABLE = 'download proxy returning 503 for slug "%s": authorization failed at stage "%s".';
    public const UPDATE_LOG_PRE_DOWNLOAD_RESOLVE_FAILED = 'in-process package resolve failed for slug "%s" at stage "%s".';
    public const UPDATE_LOG_PRE_DOWNLOAD_FETCH_FAILED = 'in-process package fetch failed for slug "%s": %s';
    public const UPDATE_FAILURE_STAGE_BASE_URL_MISSING = 'base_url_missing';
    public const UPDATE_FAILURE_STAGE_CHECK_FAILED = 'update_check_failed';
    public const UPDATE_FAILURE_STAGE_NO_UPDATE_VERSION = 'no_update_version';
    public const UPDATE_FAILURE_STAGE_AUTHORIZE_FAILED = 'license_authorize_failed';
    public const UPDATE_FAILURE_STAGE_UNKNOWN = 'unknown';
    public const UPDATE_ERROR_CODE_PACKAGE_RESOLVE_FAILED = 'fred_cloud_update_package_resolve_failed';
    public const UPDATE_ERROR_CODE_PACKAGE_FETCH_FAILED = 'fred_cloud_update_package_fetch_failed';
    public const UPDATE_ERROR_MESSAGE_PACKAGE_RESOLVE_FAILED = 'Could not resolve the update download for "%s" from the license server (stage: %s). The in-process downloader bypassed the site-local proxy; verify the license server is reachable from this host.';
    public const UPDATE_ERROR_MESSAGE_PACKAGE_FETCH_FAILED = 'Downloading the update for "%s" from the license server failed: %s';
    public const UPDATE_ERROR_DETAIL_UNKNOWN = 'unknown error';
}
